### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by GromozavrStas**

### CODE REVIEW

**Comment by woalk** [comment]
Thank you for participation!

I think there is a typo in pref_apps_increase_onupdate_summary ("устан**о**влевает", last line).

_You should note that adding a translation in a developing app means that you have to maintain it a while._

**Comment by GromozavrStas** [comment]
Yes Projects interesting to me, I want to support it.
I do typo correct "устанавливает"
Now I can not fix. I'm at work

**Comment by woalk** [comment]
It still does not evaluate by e.g. Google Translate.
The word seems cursed for you... ;) (устанавл**и**вает, if I'm not mistaken. Correct me if Google Translate is wrong there, but I doubt it.)

I would fix myself, but even small steps made by others help me in managing my time.
I don't want to add translations manually by myself, I focus on function development.

Thank you!

**Comment by woalk** [comment]
Please include the locale (RU in your case) for future commits of this.

Thank you!

**Pull request merged**
